<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommerceEnhancementsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('return_requests')->insert([
            [
                'order_id' => 3,
                'order_item_id' => 3,
                'user_id' => 4,
                'reason' => 'not_as_described',
                'description' => 'The product does not match the screenshots shown.',
                'status' => 'received',
                'resolution' => 'refund',
                'admin_notes' => 'Item received in good condition. Processing refund.',
                'processed_by' => 1,
                'processed_at' => '2026-05-28 16:00:00',
            ],
            [
                'order_id' => 2,
                'order_item_id' => 2,
                'user_id' => 3,
                'reason' => 'changed_mind',
                'description' => 'I no longer need this software.',
                'status' => 'approved',
                'resolution' => 'store_credit',
                'admin_notes' => 'Approved store credit as requested by customer.',
                'processed_by' => 1,
                'processed_at' => '2026-05-25 10:00:00',
            ],
        ]);

        DB::table('reviews')->insert([
            [
                'reviewable_type' => 'product',
                'reviewable_id' => 1,
                'user_id' => 2,
                'order_id' => 1,
                'rating' => 5,
                'title' => 'Excellent script!',
                'body' => 'This is exactly what I needed. Easy to install and configure.',
                'is_approved' => true,
                'is_verified_purchase' => true,
                'created_at' => '2026-04-28 10:00:00',
            ],
            [
                'reviewable_type' => 'product',
                'reviewable_id' => 1,
                'user_id' => 3,
                'order_id' => 2,
                'rating' => 4,
                'title' => 'Great but needs docs',
                'body' => 'Works well but documentation could be better.',
                'is_approved' => true,
                'is_verified_purchase' => true,
                'created_at' => '2026-04-29 10:00:00',
            ],
            [
                'reviewable_type' => 'product',
                'reviewable_id' => 2,
                'user_id' => 3,
                'order_id' => 3,
                'rating' => 3,
                'title' => 'Decent plugin',
                'body' => 'Does the job but has some bugs.',
                'is_approved' => false,
                'is_verified_purchase' => true,
                'created_at' => '2026-05-01 10:00:00',
            ],
            [
                'reviewable_type' => 'product',
                'reviewable_id' => 3,
                'user_id' => 3,
                'order_id' => 2,
                'rating' => 5,
                'title' => 'Best SaaS platform',
                'body' => 'Highly recommend for any business.',
                'is_approved' => true,
                'is_verified_purchase' => true,
                'created_at' => '2026-04-30 10:00:00',
            ],
            [
                'reviewable_type' => 'seller',
                'reviewable_id' => 2,
                'user_id' => 3,
                'order_id' => 1,
                'rating' => 5,
                'title' => null,
                'body' => 'Excellent service, instant license delivery!',
                'is_approved' => true,
                'is_verified_purchase' => false,
                'created_at' => '2026-05-12 14:00:00',
            ],
            [
                'reviewable_type' => 'seller',
                'reviewable_id' => 2,
                'user_id' => 4,
                'order_id' => 1,
                'rating' => 4,
                'title' => null,
                'body' => 'Good product, would recommend.',
                'is_approved' => true,
                'is_verified_purchase' => false,
                'created_at' => '2026-05-13 09:30:00',
            ],
        ]);

        DB::table('wishlist_items')->insert([
            [
                'wishlist_id' => 1,
                'product_id' => 1,
                'notes' => 'Wait for sale',
            ],
            [
                'wishlist_id' => 1,
                'product_id' => 2,
                'notes' => null,
            ],
            [
                'wishlist_id' => 2,
                'product_id' => 3,
                'notes' => 'For brother',
            ],
            [
                'wishlist_id' => 3,
                'product_id' => 1,
                'notes' => null,
            ],
        ]);

        DB::table('user_payment_methods')->insert([
            [
                'user_id' => 1,
                'gateway_id' => null,
                'method_type' => 'card',
                'gateway_token' => 'tok_visa_4242',
                'display_name' => 'Visa ending in 4242',
                'last_four' => '4242',
                'expiry_month' => '12',
                'expiry_year' => '2028',
                'card_brand' => 'Visa',
                'is_default' => true,
            ],
            [
                'user_id' => 1,
                'gateway_id' => null,
                'method_type' => 'paypal',
                'gateway_token' => 'paypal_merchant_1',
                'display_name' => 'My PayPal',
                'last_four' => null,
                'expiry_month' => null,
                'expiry_year' => null,
                'card_brand' => null,
                'is_default' => false,
            ],
            [
                'user_id' => 2,
                'gateway_id' => null,
                'method_type' => 'card',
                'gateway_token' => 'tok_mc_5555',
                'display_name' => 'Mastercard Business',
                'last_four' => '5555',
                'expiry_month' => '08',
                'expiry_year' => '2027',
                'card_brand' => 'Mastercard',
                'is_default' => true,
            ],
            [
                'user_id' => 3,
                'gateway_id' => null,
                'method_type' => 'card',
                'gateway_token' => 'tok_amex_3000',
                'display_name' => 'Amex Platinum',
                'last_four' => '3000',
                'expiry_month' => '03',
                'expiry_year' => '2029',
                'card_brand' => 'Amex',
                'is_default' => true,
            ],
        ]);

        DB::table('user_addresses')->insert([
            [
                'user_id' => 1,
                'label' => 'Home',
                'first_name' => null,
                'last_name' => null,
                'full_name' => 'Admin User',
                'phone' => '+12025551234',
                'address_line1' => '123 Main St',
                'address_line2' => null,
                'city' => 'New York',
                'state' => 'NY',
                'postal_code' => '10001',
                'country' => 'United States',
                'is_default_billing' => true,
                'is_default_shipping' => true,
            ],
            [
                'user_id' => 2,
                'label' => 'Office',
                'first_name' => null,
                'last_name' => null,
                'full_name' => 'John Doe',
                'phone' => '+12025551235',
                'address_line1' => '456 Oak Ave',
                'address_line2' => null,
                'city' => 'Los Angeles',
                'state' => 'CA',
                'postal_code' => '90001',
                'country' => 'United States',
                'is_default_billing' => true,
                'is_default_shipping' => false,
            ],
            [
                'user_id' => 3,
                'label' => 'Home',
                'first_name' => null,
                'last_name' => null,
                'full_name' => 'Jane Smith',
                'phone' => '+12025551236',
                'address_line1' => '789 Pine Rd',
                'address_line2' => null,
                'city' => 'Chicago',
                'state' => 'IL',
                'postal_code' => '60601',
                'country' => 'United States',
                'is_default_billing' => false,
                'is_default_shipping' => true,
            ],
            [
                'user_id' => 3,
                'label' => 'Home',
                'first_name' => 'John',
                'last_name' => 'Buyer',
                'full_name' => 'John Buyer',
                'phone' => '+1-555-0102',
                'address_line1' => '123 Main Street, Apt 4B',
                'address_line2' => null,
                'city' => 'New York',
                'state' => 'NY',
                'postal_code' => '10001',
                'country' => 'US',
                'is_default_billing' => true,
                'is_default_shipping' => true,
            ],
            [
                'user_id' => 3,
                'label' => 'Office',
                'first_name' => 'John',
                'last_name' => 'Buyer',
                'full_name' => 'John Buyer',
                'phone' => '+1-555-0199',
                'address_line1' => '456 Corporate Blvd, Suite 200',
                'address_line2' => null,
                'city' => 'New York',
                'state' => 'NY',
                'postal_code' => '10002',
                'country' => 'US',
                'is_default_billing' => true,
                'is_default_shipping' => false,
            ],
            [
                'user_id' => 2,
                'label' => 'Home',
                'first_name' => 'CodeMaster',
                'last_name' => 'Dev',
                'full_name' => 'CodeMaster Dev',
                'phone' => '+1-555-0101',
                'address_line1' => '789 Developer Lane',
                'address_line2' => null,
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94105',
                'country' => 'US',
                'is_default_billing' => true,
                'is_default_shipping' => true,
            ],
        ]);

        DB::table('personal_access_tokens')->insert([
            [
                'user_id' => 1,
                'name' => 'API Integration',
                'token' => 'pat_api_integration_abc123def456',
                'abilities' => '["read","write"]',
                'expires_at' => null,
            ],
            [
                'user_id' => 2,
                'name' => 'CI/CD Pipeline',
                'token' => 'pat_cicd_ghi789jkl012',
                'abilities' => '["read"]',
                'expires_at' => '2027-01-01 00:00:00',
            ],
            [
                'user_id' => 3,
                'name' => 'Mobile App Access',
                'token' => 'pat_mobile_mno345pqr678',
                'abilities' => '["read","write","push"]',
                'expires_at' => null,
            ],
        ]);

        DB::table('sessions')->insert([
            [
                'id' => 'sess_admin_001',
                'user_id' => 1,
                'ip_address' => '192.168.1.100',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120',
                'payload' => '{"data":"session_data"}',
                'last_activity' => 1717200000,
            ],
            [
                'id' => 'sess_user_002',
                'user_id' => 3,
                'ip_address' => '10.0.0.50',
                'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0) Mobile/15E148',
                'payload' => '{"data":"session_data"}',
                'last_activity' => 1717199000,
            ],
            [
                'id' => 'sess_guest_003',
                'user_id' => null,
                'ip_address' => '172.16.0.10',
                'user_agent' => 'Mozilla/5.0 (Linux; Android 14) SamsungBrowser/24',
                'payload' => '{"data":"guest_data"}',
                'last_activity' => 1717198000,
            ],
        ]);

        DB::table('social_accounts')->insert([
            [
                'user_id' => 1,
                'provider' => 'google',
                'provider_id' => 'google_uid_12345',
                'provider_email' => 'admin@gmail.com',
                'avatar_url' => 'https://lh3.googleusercontent.com/a/photo1',
            ],
            [
                'user_id' => 3,
                'provider' => 'github',
                'provider_id' => 'github_uid_67890',
                'provider_email' => 'jane@github.com',
                'avatar_url' => 'https://avatars.githubusercontent.com/u/67890',
            ],
        ]);

        DB::table('user_devices')->insert([
            [
                'user_id' => 1,
                'platform' => 'web',
                'device_token' => 'web_push_token_admin_001',
                'device_name' => 'Chrome on Desktop',
                'fingerprint' => null,
                'ip_address' => null,
                'user_agent' => null,
                'is_active' => true,
                'last_active_at' => null,
                'last_notified_at' => null,
            ],
            [
                'user_id' => 3,
                'platform' => 'ios',
                'device_token' => 'apns_token_iphone_jane_001',
                'device_name' => 'Jane\'s iPhone 15',
                'fingerprint' => null,
                'ip_address' => null,
                'user_agent' => null,
                'is_active' => true,
                'last_active_at' => null,
                'last_notified_at' => null,
            ],
            [
                'user_id' => 4,
                'platform' => 'android',
                'device_token' => 'fcm_token_pixel_001',
                'device_name' => 'Pixel 8 Pro',
                'fingerprint' => null,
                'ip_address' => null,
                'user_agent' => null,
                'is_active' => true,
                'last_active_at' => null,
                'last_notified_at' => null,
            ],
            [
                'user_id' => 1,
                'platform' => 'android',
                'device_token' => 'fcm_token_tablet_001',
                'device_name' => 'Samsung Tablet',
                'fingerprint' => null,
                'ip_address' => null,
                'user_agent' => null,
                'is_active' => false,
                'last_active_at' => null,
                'last_notified_at' => null,
            ],
            [
                'user_id' => 3,
                'platform' => 'web',
                'device_token' => 'fp_token_chrome_001',
                'device_name' => 'Chrome on Windows',
                'fingerprint' => 'fp-chrome-win10-a1b2c3',
                'ip_address' => '192.168.1.100',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'is_active' => true,
                'last_active_at' => '2026-05-30 14:30:00',
                'last_notified_at' => null,
            ],
            [
                'user_id' => 3,
                'platform' => 'web',
                'device_token' => 'fp_token_firefox_002',
                'device_name' => 'Firefox on Windows',
                'fingerprint' => 'fp-firefox-win10-d4e5f6',
                'ip_address' => '192.168.1.100',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0',
                'is_active' => true,
                'last_active_at' => '2026-05-29 09:15:00',
                'last_notified_at' => null,
            ],
        ]);
    }
}
