<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrdersCommerceSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('coupons')->insert([
            [
                'id' => 1,
                'code' => 'WELCOME20',
                'type' => 'percentage',
                'value' => 20.00,
                'min_order_amount' => 0,
                'max_uses' => 100,
                'used_count' => 2,
                'starts_at' => '2026-01-01 00:00:00',
                'expires_at' => '2027-01-01 00:00:00',
                'is_active' => true,
            ],
            [
                'id' => 2,
                'code' => 'FLAT10',
                'type' => 'fixed_amount',
                'value' => 10.00,
                'min_order_amount' => 50,
                'max_uses' => 50,
                'used_count' => 0,
                'starts_at' => '2026-01-01 00:00:00',
                'expires_at' => '2026-12-31 00:00:00',
                'is_active' => true,
            ],
            [
                'id' => 3,
                'code' => 'EXPIRED50',
                'type' => 'percentage',
                'value' => 50.00,
                'min_order_amount' => 0,
                'max_uses' => 10,
                'used_count' => 10,
                'starts_at' => '2025-01-01 00:00:00',
                'expires_at' => '2025-12-31 00:00:00',
                'is_active' => false,
            ],
            [
                'code' => 'LAUNCH20',
                'type' => 'percentage',
                'value' => 20.00,
                'min_order_amount' => 10.00,
                'max_uses' => 100,
                'used_count' => 5,
                'starts_at' => '2026-01-01 00:00:00',
                'expires_at' => '2026-12-31 23:59:59',
                'is_active' => true,
            ],
            [
                'code' => 'SAVE10',
                'type' => 'fixed_amount',
                'value' => 10.00,
                'min_order_amount' => null,
                'max_uses' => 500,
                'used_count' => 42,
                'starts_at' => '2026-03-01 00:00:00',
                'expires_at' => '2026-09-30 23:59:59',
                'is_active' => true,
            ],
            [
                'code' => 'VIP50',
                'type' => 'percentage',
                'value' => 50.00,
                'min_order_amount' => 50.00,
                'max_uses' => 10,
                'used_count' => 0,
                'starts_at' => '2026-06-01 00:00:00',
                'expires_at' => '2026-07-31 23:59:59',
                'is_active' => true,
            ],
            [
                'code' => 'EXPIRED10',
                'type' => 'percentage',
                'value' => 10.00,
                'min_order_amount' => null,
                'max_uses' => null,
                'used_count' => 0,
                'starts_at' => '2025-01-01 00:00:00',
                'expires_at' => '2025-06-30 23:59:59',
                'is_active' => false,
            ],
        ]);

        DB::table('carts')->insert([
            [
                'id' => 1,
                'user_id' => 3,
                'coupon_id' => null,
                'subtotal' => 149.00,
                'tax' => 14.90,
                'total' => 163.90,
            ],
            [
                'id' => 2,
                'user_id' => 3,
                'coupon_id' => 1,
                'subtotal' => 59.00,
                'tax' => 5.90,
                'total' => 51.82,
            ],
            [
                'user_id' => 3,
                'coupon_id' => null,
                'subtotal' => 0.00,
                'tax' => 0.00,
                'total' => 0.00,
                'expires_at' => '2026-06-04 14:00:00',
            ],
            [
                'user_id' => 3,
                'coupon_id' => null,
                'subtotal' => 0.00,
                'tax' => 0.00,
                'total' => 0.00,
                'expires_at' => '2026-05-28 14:00:00',
            ],
        ]);

        DB::table('cart_items')->insert([
            [
                'cart_id' => 1,
                'product_id' => 3,
                'plan_id' => null,
                'quantity' => 1,
                'unit_price' => 149.00,
                'subtotal' => 149.00,
            ],
            [
                'cart_id' => 2,
                'product_id' => 1,
                'plan_id' => 2,
                'quantity' => 1,
                'unit_price' => 59.00,
                'subtotal' => 59.00,
            ],
            [
                'cart_id' => 1,
                'product_id' => 1,
                'plan_id' => null,
                'quantity' => 1,
                'unit_price' => 59.00,
                'subtotal' => 59.00,
            ],
            [
                'cart_id' => 1,
                'product_id' => 2,
                'plan_id' => null,
                'quantity' => 2,
                'unit_price' => 29.00,
                'subtotal' => 58.00,
            ],
            [
                'cart_id' => 2,
                'product_id' => 3,
                'plan_id' => null,
                'quantity' => 1,
                'unit_price' => 99.00,
                'subtotal' => 99.00,
            ],
        ]);

        DB::table('orders')->insert([
            [
                'id' => 1,
                'user_id' => 3,
                'order_number' => 'ORD-2026-00001',
                'status' => 'completed',
                'subtotal' => 299.00,
                'tax' => 29.90,
                'discount_total' => 0.00,
                'total' => 328.90,
                'currency' => 'USD',
                'billing_address_id' => 1,
                'coupon_id' => null,
                'api_client_id' => 1,
                'customer_notes' => null,
                'ip_address' => '192.168.1.100',
                'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'paid_at' => '2026-05-01 00:05:00',
                'cancelled_at' => null,
                'created_at' => '2026-05-01 00:00:00',
            ],
            [
                'id' => 2,
                'user_id' => 3,
                'order_number' => 'ORD-2026-00002',
                'status' => 'cancelled',
                'subtotal' => 9.99,
                'tax' => 0.00,
                'discount_total' => 0.00,
                'total' => 9.99,
                'currency' => 'USD',
                'billing_address_id' => 1,
                'coupon_id' => null,
                'api_client_id' => 2,
                'customer_notes' => 'Requested cancellation via support chat',
                'ip_address' => '10.0.0.55',
                'user_agent' => 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/537.36',
                'paid_at' => null,
                'cancelled_at' => '2026-04-01 00:05:00',
                'created_at' => '2026-04-01 00:00:00',
            ],
            [
                'id' => 3,
                'user_id' => 2,
                'order_number' => 'ORD-2026-00003',
                'status' => 'pending',
                'subtotal' => 59.00,
                'tax' => 5.90,
                'discount_total' => 0.00,
                'total' => 64.90,
                'currency' => 'USD',
                'billing_address_id' => 3,
                'coupon_id' => null,
                'api_client_id' => null,
                'customer_notes' => null,
                'ip_address' => '203.0.113.50',
                'user_agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
                'paid_at' => null,
                'cancelled_at' => null,
                'created_at' => '2026-05-30 12:00:00',
            ],
        ]);

        DB::table('order_items')->insert([
            [
                'order_id' => 1,
                'product_id' => 1,
                'plan_id' => 2,
                'item_type' => 'subscription',
                'name' => 'Ultimate CRM Script (Professional Plan)',
                'quantity' => 1,
                'unit_price' => 299.00,
                'subtotal' => 299.00,
            ],
            [
                'order_id' => 2,
                'product_id' => 3,
                'plan_id' => 1,
                'item_type' => 'subscription',
                'name' => 'Desktop Inventory Manager (Starter Plan)',
                'quantity' => 1,
                'unit_price' => 9.99,
                'subtotal' => 9.99,
            ],
            [
                'order_id' => 3,
                'product_id' => 2,
                'plan_id' => null,
                'item_type' => 'product',
                'name' => 'SaaS Boilerplate',
                'quantity' => 1,
                'unit_price' => 59.00,
                'subtotal' => 59.00,
            ],
        ]);

        DB::table('order_item_metadata')->insert([
            [
                'order_item_id' => 1,
                'license_id' => 1,
                'meta_key' => 'license_key',
                'meta_value' => 'LIC-PRO-2026-8888',
            ],
            [
                'order_item_id' => 1,
                'license_id' => 1,
                'meta_key' => 'subscription_id',
                'meta_value' => '1',
            ],
            [
                'order_item_id' => 1,
                'license_id' => 1,
                'meta_key' => 'activation_count',
                'meta_value' => '2',
            ],
            [
                'order_item_id' => 2,
                'license_id' => 2,
                'meta_key' => 'license_key',
                'meta_value' => 'LIC-DESKTOP-2026-9999',
            ],
            [
                'order_item_id' => 2,
                'license_id' => 2,
                'meta_key' => 'subscription_id',
                'meta_value' => '1',
            ],
            [
                'order_item_id' => 3,
                'license_id' => null,
                'meta_key' => 'notes',
                'meta_value' => 'Awaiting payment confirmation to generate license',
            ],
        ]);

        DB::table('order_status_history')->insert([
            [
                'order_id' => 1,
                'from_status' => null,
                'to_status' => 'pending',
                'changed_by' => null,
                'api_client_id' => 1,
                'reason' => 'Order placed via API',
                'created_at' => '2026-05-01 00:00:00',
            ],
            [
                'order_id' => 1,
                'from_status' => 'pending',
                'to_status' => 'confirmed',
                'changed_by' => null,
                'api_client_id' => null,
                'reason' => 'Payment received',
                'created_at' => '2026-05-01 00:05:00',
            ],
            [
                'order_id' => 1,
                'from_status' => 'confirmed',
                'to_status' => 'processing',
                'changed_by' => null,
                'api_client_id' => null,
                'reason' => 'Subscription activated',
                'created_at' => '2026-05-01 00:06:00',
            ],
            [
                'order_id' => 1,
                'from_status' => 'processing',
                'to_status' => 'completed',
                'changed_by' => null,
                'api_client_id' => null,
                'reason' => 'License generated and provisioned',
                'created_at' => '2026-05-01 00:10:00',
            ],
            [
                'order_id' => 2,
                'from_status' => null,
                'to_status' => 'pending',
                'changed_by' => null,
                'api_client_id' => 2,
                'reason' => 'Order placed via API staging',
                'created_at' => '2026-04-01 00:00:00',
            ],
            [
                'order_id' => 2,
                'from_status' => 'pending',
                'to_status' => 'cancelled',
                'changed_by' => 3,
                'api_client_id' => null,
                'reason' => 'User requested cancellation',
                'created_at' => '2026-04-01 00:05:00',
            ],
            [
                'order_id' => 3,
                'from_status' => null,
                'to_status' => 'pending',
                'changed_by' => null,
                'api_client_id' => null,
                'reason' => 'Order placed via web',
                'created_at' => '2026-05-30 12:00:00',
            ],
        ]);

        DB::table('refunds')->insert([
            [
                'order_id' => 2,
                'payment_id' => null,
                'amount' => 9.99,
                'reason' => 'Order cancelled before payment — auto refund initiated',
                'status' => 'approved',
                'processed_by' => 1,
                'created_at' => '2026-04-01 12:00:00',
            ],
            [
                'order_id' => 1,
                'payment_id' => 1,
                'amount' => 328.90,
                'reason' => 'Customer requested full refund due to installation issues',
                'status' => 'completed',
                'processed_by' => 1,
                'created_at' => '2026-05-05 14:00:00',
            ],
            [
                'order_id' => 3,
                'payment_id' => null,
                'amount' => 29.00,
                'reason' => 'Item not as described',
                'status' => 'completed',
                'processed_by' => 1,
            ],
            [
                'order_id' => 2,
                'payment_id' => null,
                'amount' => 9.99,
                'reason' => 'Changed mind',
                'status' => 'pending',
                'processed_by' => null,
            ],
        ]);

        DB::table('shipments')->insert([
            [
                'order_id' => 1,
                'tracking_number' => '1Z999AA10123456784',
                'carrier' => 'UPS',
                'status' => 'delivered',
                'shipped_at' => '2026-05-02 10:00:00',
                'delivered_at' => '2026-05-05 14:00:00',
                'shipping_data' => json_encode(['weight_kg' => 0.5, 'service' => 'ground']),
            ],
            [
                'order_id' => 2,
                'tracking_number' => '940011189922345678',
                'carrier' => 'USPS',
                'status' => 'returned',
                'shipped_at' => '2026-04-02 10:00:00',
                'delivered_at' => '2026-04-10 10:00:00',
                'shipping_data' => json_encode(['weight_kg' => 0.2, 'service' => 'first_class']),
            ],
        ]);

        DB::table('file_downloads')->insert([
            [
                'order_item_id' => 3,
                'user_id' => 2,
                'ip_address' => '203.0.113.50',
                'download_count' => 1,
                'last_downloaded' => '2026-05-30 12:05:00',
                'expires_at' => '2026-06-29 12:00:00',
            ],
            [
                'order_item_id' => 3,
                'user_id' => 2,
                'ip_address' => '203.0.113.51',
                'download_count' => 0,
                'last_downloaded' => null,
                'expires_at' => '2026-06-29 12:00:00',
            ],
        ]);

        DB::table('affiliates')->insert([
            [
                'id' => 1,
                'user_id' => 3,
                'code' => 'JOHN-BUYER-10',
                'commission_rate' => 15.00,
                'total_earned' => 29.90,
                'total_paid' => 0.00,
                'status' => 'active',
            ],
            [
                'id' => 2,
                'user_id' => 4,
                'code' => 'SARAH-SUPPORT-10',
                'commission_rate' => 10.00,
                'total_earned' => 5.00,
                'total_paid' => 5.00,
                'status' => 'active',
            ],
        ]);

        DB::table('referrals')->insert([
            [
                'affiliate_id' => 1,
                'referred_id' => 2,
                'order_id' => 3,
                'commission' => 8.85,
                'status' => 'pending',
                'created_at' => '2026-05-30 12:00:00',
            ],
            [
                'affiliate_id' => 2,
                'referred_id' => 1,
                'order_id' => 1,
                'commission' => 5.00,
                'status' => 'paid',
                'created_at' => '2026-05-01 00:00:00',
            ],
        ]);
    }
}
